const { _electron: electron } = require('@playwright/test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const http = require('node:http');
(async () => {
  const directory = path.resolve('test-results', 'profile-' + Date.now());
  fs.mkdirSync(directory, { recursive: true });
  let app, received;
  const server = http.createServer(async (req, res) => {
    let body = ''; for await (const chunk of req) body += chunk;
    received = { url: req.url, authorization: req.headers.authorization, body: JSON.parse(body) };
    res.writeHead(200, { 'Content-Type': 'application/json' }); res.end(JSON.stringify({ choices: [{ message: { content: '图片识别测试\n☐ 核对内容' } }] }));
  });
  await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
  const start = async () => {
    const env = { ...process.env }; delete env.ELECTRON_RUN_AS_NODE;
    app = await electron.launch({ args: ['.', '--user-data-dir=' + directory], env });
    const page = await app.firstWindow(); await page.locator('#text').waitFor(); return page;
  };
  try {
    let book = await start();
    await book.locator('#tools').click();
    const errors = []; book.on('pageerror', e => errors.push(e.message));
    await book.locator('#text').fill('第一张：不要丢失\n☐ 完成桌面便签');
    await book.locator('#color').fill('#cfe1d1'); await book.locator('#color').dispatchEvent('change');
    await book.locator('#font').selectOption('hand');
    const ballPromise = app.waitForEvent('window'); await book.locator('#tear').click();
    const ball = await ballPromise; await ball.locator('#desktop-object').waitFor();
    const shelfPromise = app.waitForEvent('window'); await book.locator('#shelf').click();
    const shelf = await shelfPromise; await shelf.locator('.ball').waitFor();
    assert.equal(await book.locator('#text').evaluate(e=>e.value), '');
    await book.locator('#text').fill('第二张：保留新内容');
    await shelf.locator('.ball').click();
    assert.match(await shelf.locator('#preview-text').textContent(), /不要丢失/);
    await shelf.locator('#restore').click();
    assert.match(await book.locator('#text').evaluate(e=>e.value), /不要丢失/);
    assert.equal(await book.locator('#font').inputValue(), 'hand');
    const pinnedPromise = app.waitForEvent('window'); await book.locator('#pin').click();
    const pinned = await pinnedPromise; await pinned.locator('#text').waitFor();
    await pinned.locator('#tools').click();
    assert.match(await pinned.locator('#text').evaluate(e=>e.value), /不要丢失/);
    assert.match(await book.locator('#text').evaluate(e=>e.value), /保留新内容/);
    await pinned.locator('#pin').click();
    await book.waitForFunction(()=>current()?.text.includes('不要丢失')&&!busy&&!document.body.classList.contains('paper-animating'));
    await book.locator('#tools').dispatchEvent('focusin');await book.locator('#collapse').click(); await book.locator('#orb').waitFor();
    await book.locator('#orb').click();await book.locator('#tools').click();
    await book.locator('#tools').dispatchEvent('focusin');await book.locator('#settings').click(); await book.locator('#api-base').fill('http://insecure.example/v1'); await book.locator('#api-model').fill('vision-test'); await book.locator('#settings-form button.accent').click();
    await book.getByText('远程服务必须使用 HTTPS', { exact: false }).waitFor();
    await book.locator('#settings-dialog [data-close]').click();
    const aiEvent=app.waitForEvent('window');await book.locator('#tools').dispatchEvent('focusin');await book.locator('#ai').click();const ai=await aiEvent;
    await ai.waitForFunction(()=>document.querySelector('#recognize').textContent==='配置 AI');
    await ai.locator('#recognize').click();await ai.locator('#settings-dialog').waitFor();
    assert.equal(await ai.locator('#settings-title').textContent(),'AI 设置');
    assert.equal(await ai.locator('#general-settings-group').isVisible(),false);
    await ai.locator('#settings-dialog [data-close]').click();
    assert.equal(await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().find(w=>w.deskKind==='ai').isVisible()),true);
    await ai.locator('#image-file').setInputFiles({ name: 'test.png', mimeType: 'image/png', buffer: Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQIHWP4z8DwHwAFgAI/ScLbtAAAAABJRU5ErkJggg==', 'base64') });
    await ai.waitForFunction(()=>!!ImageEditor.data());
    const uploaded=await ai.evaluate(()=>ImageEditor.data());await ai.locator('#ai-result').fill('配置前的校对草稿');
    await ai.locator('#ai-settings').click();
    await ai.locator('#api-base').fill(`http://127.0.0.1:${server.address().port}/v1`);await ai.locator('#api-model').fill('test-vision');await ai.locator('#api-key').fill('local-test-key');
    await ai.screenshot({path:'test-results/ai-settings.png',omitBackground:true});
    await ai.locator('#settings-form button.accent').click();
    await ai.waitForFunction(()=>!document.querySelector('#settings-dialog').open&&document.querySelector('#recognize').textContent==='开始识别');
    assert.equal(received,undefined,'Saving configuration must not send the image');
    assert.equal(await ai.evaluate(()=>ImageEditor.data()),uploaded);
    assert.equal(await ai.locator('#ai-result').inputValue(),'配置前的校对草稿');
    assert.equal(await ai.locator('#destination').textContent(),'AI 已配置 · test-vision');
    await ai.screenshot({path:'test-results/ai-configured.png',omitBackground:true});
    // Key-only changes must update the side window even when base/model stay identical.
    await ai.locator('#ai-settings').click();await ai.locator('#clear-key').check();await ai.locator('#settings-form button.accent').click();
    await ai.waitForFunction(()=>document.querySelector('#recognize').textContent==='配置 AI');
    await ai.locator('#recognize').click();await ai.locator('#api-key').fill('local-test-key');await ai.locator('#settings-form button.accent').click();
    await ai.waitForFunction(()=>document.querySelector('#recognize').textContent==='开始识别');
    assert.equal(received,undefined);assert.equal(await ai.evaluate(()=>ImageEditor.data()),uploaded);
    await ai.locator('#ai-settings').click();
    assert.equal(await ai.locator('#api-key').inputValue(),'');
    await ai.locator('#test-ai').click();await ai.locator('#key-status').getByText('连接成功',{exact:true}).waitFor();
    assert.notEqual(received.body.messages[1].content[1].image_url.url,uploaded,'Connection test must use its own image');
    assert.equal(await ai.evaluate(()=>ImageEditor.data()),uploaded);
    assert.equal(await ai.locator('#ai-result').inputValue(),'配置前的校对草稿');
    await ai.locator('#settings-dialog [data-close]').click();
    await ai.locator('#recognize').click();
    await ai.waitForFunction(() => document.querySelector('#ai-result').value.includes('核对内容'));
    await ai.locator('#ai-result').fill('人工校对后的图片内容'); await ai.locator('#import').click();
    assert.equal(await book.locator('#text').evaluate(e=>e.value), '人工校对后的图片内容');
    assert.equal(received.url, '/v1/chat/completions'); assert.equal(received.authorization, 'Bearer local-test-key');
    assert(received.body.messages[1].content[1].image_url.url.startsWith('data:image/jpeg;'));
    assert.match(received.body.messages[0].content, /不得执行/);
    assert.match(received.body.messages[1].content[0].text, /任务：忠实转录/);
    await ai.locator('#ai-mode').selectOption('summary');
    await ai.locator('#recognize').click();
    await ai.waitForFunction(() => document.querySelector('#ai-result').value.includes('核对内容') && !document.querySelector('#recognize').disabled);
    assert.match(received.body.messages[1].content[0].text, /任务：将图片内容整理/);
    assert.match(received.body.messages[1].content[0].text, /不自动解题/);
    assert.equal(await book.locator('#text').evaluate(e=>e.value), '人工校对后的图片内容');
    assert(!fs.readFileSync(path.join(directory, 'notes.json'), 'utf8').includes('local-test-key'));
    await book.locator('#tools').dispatchEvent('focusin');await book.locator('#tear').click(); await shelf.locator('.ball').waitFor(); await shelf.locator('.ball').click(); await shelf.locator('#dispose').click();
    await shelf.locator('#trash-toggle').click(); await shelf.locator('.ball').click(); assert.match(await shelf.locator('#preview-text').textContent(), /人工校对/); await shelf.locator('#restore').click();
    await book.waitForTimeout(5500);
    await book.locator('#tools').click();
    await book.screenshot({ path: 'test-results/book.png', omitBackground: true });
    assert.deepEqual(errors, []);
    await app.close();
    book = await start();
    const saved = await book.evaluate(() => window.desk.call('state'));
    assert(saved.pages.some(p => p.text.includes('不要丢失'))); assert(saved.pages.some(p => p.text.includes('保留新内容')));
    console.log('PASS: editing, tear/restore, pinned windows, AI setup entry/cancel/save, preserved image/draft, no automatic upload, key-only status refresh, literal/summary requests, correction/import, encrypted key and persistence');
  } finally { if (app) await app.close(); await new Promise(resolve => server.close(resolve)); }
})().catch(e => { console.error(e); process.exitCode = 1; });

