const{_electron:electron}=require('@playwright/test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
(async()=>{const profile=path.resolve('test-results','rich-'+Date.now());fs.mkdirSync(profile,{recursive:true});const env={...process.env};delete env.ELECTRON_RUN_AS_NODE;let app;const start=async()=>{app=await electron.launch({args:['.','--user-data-dir='+profile],env});app.context().setDefaultTimeout(12000);const p=await app.firstWindow();await p.locator('#text').waitFor();return p};try{const legacy=require('../src/model.cjs').initial();legacy.pages[0].text='☐ 旧待办\n☑ 已完成';fs.writeFileSync(path.join(profile,'notes.json'),JSON.stringify(legacy));let p=await start();assert.equal(await p.locator('#text .todo-check').count(),2);await p.locator('#text').fill('普通 重点 后文');await p.locator('#tools').click();await p.locator('#text').evaluate(e=>{e.focus();e.setSelectionRange(3,5)});await p.locator('#bold').click();await p.locator('#tool-options').evaluate(e=>e.open=true);await p.locator('#size').selectOption('28');await p.locator('#ink').fill('#cc3344');await p.locator('#ink').dispatchEvent('change');let s=await p.evaluate(()=>window.desk.call('state'));let note=s.pages.find(n=>n.text==='普通 重点 后文');if(!note)console.log(JSON.stringify(s.pages));assert(note.rich.some(r=>r.text==='重点'&&r.bold&&r.size===28&&r.ink==='#cc3344'));assert.equal(note.bold,false);
await p.locator('#text').evaluate(e=>{e.focus();e.setSelectionRange(e.value.length,e.value.length)});await p.keyboard.press('Enter');await p.locator('#todo').click();await p.keyboard.insertText('第一件事');await p.keyboard.press('Enter');await p.keyboard.insertText('第二件事');await p.locator('#text .todo-check').first().click();await p.waitForFunction(()=>document.querySelector('#text').value.includes('☑'));assert.equal(await p.locator('#text .todo-check').count(),2);await p.locator('#text').focus();await p.keyboard.press('Control+z');assert.equal(await p.locator('#text .todo-check').first().getAttribute('aria-checked'),'false');await p.keyboard.press('Control+y');assert.equal(await p.locator('#text .todo-check').first().getAttribute('aria-checked'),'true');await p.screenshot({path:'test-results/rich-editor.png',omitBackground:true});
s=await p.evaluate(()=>window.desk.call('state'));note=s.pages.find(n=>n.text.includes('第一件事'));const aiEvent=app.waitForEvent('window');await p.evaluate(id=>window.desk.call('ai-open',{id}),note.id);const ai=await aiEvent;await ai.evaluate(()=>window.desk.call('ai-import',{target:'append',text:'追加识别文本'}));await p.waitForFunction(()=>document.querySelector('#text').value.endsWith('追加识别文本'));note=(await p.evaluate(()=>window.desk.call('state'))).pages.find(n=>n.id===note.id);assert(note.rich.some(r=>r.text==='重点'&&r.ink==='#cc3344'));const original=JSON.stringify(note.rich);await p.evaluate(id=>window.desk.call('move',{id,status:'ball'}),note.id);await p.evaluate(id=>window.desk.call('move',{id,status:'book'}),note.id);await p.waitForFunction(()=>!document.body.classList.contains('motion-busy'));assert.equal(JSON.stringify((await p.evaluate(()=>window.desk.call('state'))).pages.find(n=>n.id===note.id).rich),original);await app.close();p=await start();assert.equal(await p.locator('#text .todo-check').count(),2);assert((await p.evaluate(()=>window.desk.call('state'))).pages.some(n=>n.rich?.some(r=>r.text==='重点'&&r.size===28)));await p.locator('#tools').click();await p.locator('#new').click();await p.locator('#todo').click();await p.keyboard.insertText('临时待办');await p.keyboard.press('Enter');await p.keyboard.press('Enter');assert.equal(await p.locator('#text .todo-check').count(),1);await p.locator('#text').evaluate(e=>{e.focus();e.setSelectionRange(0,e.value.length)});await p.locator('#todo').click();assert.equal(await p.locator('#text .todo-check').count(),0);await p.locator('#text').focus();await p.keyboard.press('Control+a');await p.keyboard.press('Backspace');assert.equal(await p.locator('#text').evaluate(e=>e.value),'');
const composition=await p.evaluate(async()=>{await editQueue;const field=document.querySelector('#text');field.dispatchEvent(new CompositionEvent('compositionstart',{bubbles:true}));field.textContent='中文组合输入';field.dispatchEvent(new InputEvent('input',{bubbles:true,isComposing:true,inputType:'insertCompositionText'}));const mid=await window.desk.call('state');field.dispatchEvent(new CompositionEvent('compositionend',{bubbles:true}));await editQueue;const end=await window.desk.call('state');return {mid:mid.pages[0].text,end:end.pages[0].text};});assert.equal(composition.mid,'');assert.equal(composition.end,'中文组合输入');
console.log('PASS: selection formatting, independent checkbox, Enter continuation, undo/redo, tear/restore, persistence');}finally{if(app)await app.close();}})().catch(e=>{console.error(e);process.exitCode=1});



