const {_electron:electron}=require('@playwright/test'),path=require('node:path'),assert=require('node:assert/strict');
(async()=>{
  const env={...process.env};delete env.ELECTRON_RUN_AS_NODE;
  const executablePath=process.env.PAPERDESK_TEST_EXE,profile=path.resolve('test-results','sling-'+Date.now());
  const launch=()=>electron.launch({executablePath,args:[...(executablePath?[]:['.']),'--user-data-dir='+profile],env});let app=await launch();
  async function bookWindow(){await app.firstWindow();for(let i=0;i<200;i++){const p=app.windows().find(w=>w.url().includes('kind=book'));if(p)return p;await new Promise(r=>setTimeout(r,25));}throw Error('book window missing');}
  try{
    let book=await bookWindow();await book.locator('#text[contenteditable=true]').waitFor();const errors=[];book.on('pageerror',e=>errors.push(e.message));
    async function openToy(kind){const event=app.waitForEvent('window');await book.evaluate(kind=>window.desk.call(kind),kind);const win=await event;win.on('pageerror',e=>errors.push(e.message));await win.waitForFunction(()=>typeof state!=='undefined'&&state&&typeof window.toyContainsPoint==='function');return win;}
    const sling=await openToy('sling');let bin=await openToy('bin');
    const area=await app.evaluate(({screen})=>screen.getPrimaryDisplay().workArea);
    await app.evaluate(({BrowserWindow},a)=>{for(const w of BrowserWindow.getAllWindows()){w.webContents.setBackgroundThrottling(false);if(w.deskKind==='sling')w.setBounds({x:a.x+80,y:a.y+a.height-318,width:260,height:310});if(w.deskKind==='bin')w.setBounds({x:a.x+Math.round(a.width*.7)-150,y:a.y+a.height-218,width:300,height:210});if(w.deskKind==='book')w.hide();}},area);
    async function waitRest(ball){const id=new URL(ball.url()).searchParams.get('id');await app.evaluate(async({BrowserWindow},id)=>{for(let i=0;i<500;i++){const b=BrowserWindow.getAllWindows().find(w=>w.pageId===id&&w.deskKind==='ball');if(!b||(!b.finishHandoff&&!b.fallTimer))return;await new Promise(r=>setTimeout(r,20));}throw Error('paper did not settle');},id);}
    async function makeBall(text,color){const event=app.waitForEvent('window');await book.evaluate(async({text,color})=>{const s=await window.desk.call('state'),p=s.pages.find(p=>p.status==='book');await window.desk.call('edit',{id:p.id,text,color});await window.desk.call('move',{id:p.id,status:'ball'});},{text,color});const ball=await event;ball.on('pageerror',e=>errors.push(e.message));await ball.waitForFunction(()=>typeof state!=='undefined'&&state);await waitRest(ball);return ball;}
    async function load(ball){await waitRest(ball);const pos=await app.evaluate(({BrowserWindow},id)=>{const b=BrowserWindow.getAllWindows().find(w=>w.pageId===id&&w.deskKind==='ball').getBounds(),s=BrowserWindow.getAllWindows().find(w=>w.deskKind==='sling').getBounds();return {x:b.x+46,y:b.y+48,tx:s.x+130,ty:s.y+120};},new URL(ball.url()).searchParams.get('id'));for(const [phase,x,y]of[['start',pos.x,pos.y],['move',pos.tx,pos.ty],['end',pos.tx,pos.ty]])await ball.evaluate(([phase,x,y])=>window.desk.call('gesture',{phase,x,y}),[phase,x,y]);await sling.waitForFunction(()=>document.body.classList.contains('loaded'));await sling.waitForTimeout(280);}
    async function chooseShot(target){const T=require('../src/toy-physics.js'),{s,b,area}=await app.evaluate(({BrowserWindow,screen})=>{const s=BrowserWindow.getAllWindows().find(w=>w.deskKind==='sling').getBounds(),b=BrowserWindow.getAllWindows().find(w=>w.deskKind==='bin').getBounds();return {s,b,area:screen.getDisplayMatching(s).workArea};}),g=T.geometry(b);let best,bestError=Infinity;for(let dx=-104;dx<=-8;dx+=2)for(let dy=-20;dy<=112;dy+=2){if(Math.hypot(dx,dy)>112)continue;const v=T.launch(dx,dy),start={x:s.x+(130+v.dx)*s.width/260,y:s.y+(120+v.dy)*s.height/310},p=T.predict(start,v,area,g);if(p.target===target&&(target!=='bounce'||T.shouldTip(p.impactVelocity.vx,p.impactVelocity.vy,{point:p.points.at(-1)},g,1))){const error=target==='capture'?Math.abs(p.points.at(-1).x-g.mouth.center.x):-Math.abs(p.impactVelocity.vx)*(g.pivot.y-p.points.at(-1).y);if(error<bestError){best={dx:v.dx,dy:v.dy};bestError=error;}}}if(best)return best;throw Error('no '+target+' trajectory');}
    async function aim(p){await sling.mouse.move(130,120);await sling.mouse.down();await sling.mouse.move(130+p.dx,120+p.dy,{steps:8});}
    const hitBall=await makeBall('弹弓命中后还能还原','#deebd9'),hitId=new URL(hitBall.url()).searchParams.get('id');await load(hitBall);
    assert(await sling.locator('#loaded-paper').evaluate(async e=>{const img=new Image();img.src=e.getAttribute('href');await img.decode();const c=document.createElement('canvas');c.width=c.height=72;const ctx=c.getContext('2d');ctx.drawImage(img,0,0,72,72);return img.width===72&&ctx.getImageData(36,36,1,1).data[3]>0;}),'loaded paper must be an actual colored thumbnail');
    // Moving the base while loaded must not aim or unload the paper.
    const before=await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().find(w=>w.deskKind==='sling').getBounds());
    await sling.evaluate(()=>document.querySelector('#desktop-object').addEventListener('pointerdown',e=>window.dragOrigin={x:e.screenX,y:e.screenY},{once:true}));await sling.mouse.move(130,270);await sling.mouse.down();
    await sling.evaluate(()=>{const o=window.dragOrigin,p=document.querySelector('#desktop-object');for(const type of ['pointermove','pointerup'])p.dispatchEvent(new PointerEvent(type,{bubbles:true,pointerId:1,button:0,buttons:type==='pointermove'?1:0,clientX:155,clientY:270,screenX:o.x+25,screenY:o.y}));});await sling.mouse.up();
    assert.equal((await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().find(w=>w.deskKind==='sling').getBounds())).x,before.x+25);assert(await sling.locator('body').evaluate(e=>e.classList.contains('loaded')));
    await aim({dx:-80,dy:80});await sling.screenshot({path:'test-results/sling-aim.png',omitBackground:true});const overlay=app.windows().find(p=>p.url().endsWith('/aim.html'));assert(overlay);await overlay.waitForFunction(()=>current?.mode==='aim');assert(await overlay.evaluate(()=>current.points.some(p=>p.x-current.points[0].x>600)));await sling.keyboard.press('Escape');await sling.mouse.up();assert(await sling.locator('body').evaluate(e=>e.classList.contains('loaded')));
    const shot=await chooseShot('capture');await aim(shot);let aligned=false;for(const offset of [0,1,2,-1,-2,3,-3,4,-4]){await sling.mouse.move(130+shot.dx,120+shot.dy+offset);await sling.waitForTimeout(70);if(await overlay.evaluate(()=>current?.target==='capture')){aligned=true;break;}}assert(aligned,'mouth target should be reachable with native pixel rounding');await bin.waitForFunction(()=>document.body.classList.contains('aim-target'));await overlay.screenshot({path:'test-results/trajectory.png',omitBackground:true});await sling.mouse.up();await book.waitForFunction(id=>state.pages.some(p=>p.id===id&&p.status==='trash'),hitId);await bin.waitForFunction(()=>document.querySelectorAll('#bin-fill image').length===1);await bin.screenshot({path:'test-results/bin-filled.png',omitBackground:true});
    // High side impact tips the basket but keeps its existing contents.
    await app.evaluate(({BrowserWindow})=>{const s=BrowserWindow.getAllWindows().find(w=>w.deskKind==='sling').getBounds(),b=BrowserWindow.getAllWindows().find(w=>w.deskKind==='bin');b.setPosition(s.x+390,b.getBounds().y);});
    const miss=await makeBall('撞倒垃圾桶也不会丢失','#f3dce4');await load(miss);const strong=await chooseShot('bounce');await aim(strong);await sling.mouse.up();await bin.waitForFunction(()=>binPose.tipped);await bin.waitForTimeout(750);await bin.screenshot({path:'test-results/bin-tipped.png',omitBackground:true});assert.equal((await book.evaluate(()=>window.desk.call('state'))).pages.filter(p=>p.status==='trash').length,1);await waitRest(miss);
    await bin.evaluate(()=>{window.toyHits=[];window.desk.onToy(data=>window.toyHits.push(data));});
    await load(miss);await sling.locator('#unload').click();await sling.waitForFunction(()=>!document.body.classList.contains('loaded'));await waitRest(miss);
    await load(miss);await aim({dx:80,dy:50});await sling.mouse.up();await waitRest(miss);assert((await book.evaluate(()=>window.desk.call('state'))).pages.some(p=>p.text==='撞倒垃圾桶也不会丢失'&&p.status==='ball'));
    // Transparent margins and the tilted contour consume different input.
    await app.evaluate(({BrowserWindow})=>{const w=BrowserWindow.getAllWindows().find(w=>w.deskKind==='bin');w.hide();const ignore=w.setIgnoreMouseEvents.bind(w);w.setIgnoreMouseEvents=(value,...args)=>{w.lastIgnore=value;return ignore(value,...args);};});
    await bin.evaluate(()=>{ignored=false;return window.desk.call('hit-test',{ignore:false});});
    for(const [point,expected]of [[{x:10,y:10},true],[await bin.evaluate(()=>DesktopToys.geometry({x:0,y:0,width:300,height:210},binPose.angle,binPose.direction).inside),false]]){await bin.evaluate(point=>document.body.dispatchEvent(new PointerEvent('pointermove',{bubbles:true,clientX:point.x,clientY:point.y})),point);await bin.waitForTimeout(80);assert.equal(await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().find(w=>w.deskKind==='bin').lastIgnore),expected);}
    // Pose survives process restart. Clicking the tilted body uprights it.
    await app.close();app=await launch();book=await bookWindow();await book.locator('#text[contenteditable=true]').waitFor();bin=await openToy('bin');await bin.waitForFunction(()=>binPose.tipped);const inside=await bin.evaluate(()=>DesktopToys.geometry({x:0,y:0,width:300,height:210},binPose.angle,binPose.direction).inside);await bin.mouse.click(inside.x,inside.y);await bin.waitForFunction(()=>!binPose.tipped);await bin.waitForTimeout(700);assert((await book.evaluate(()=>window.desk.call('state'))).pages.some(p=>p.text==='撞倒垃圾桶也不会丢失'&&p.status==='ball'));
    await book.evaluate(id=>window.desk.call('move',{id,status:'book'}),hitId);assert((await book.evaluate(()=>window.desk.call('state'))).pages.some(p=>p.id===hitId&&p.status==='book'&&p.text==='弹弓命中后还能还原'));
    assert.deepEqual(errors,[]);console.log('PASS: real paper load, base drag, increased range, shared trajectory, Escape, mouth capture, basket fill, strong impact tipping, restart, click upright, content restore');
  }finally{await app.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
