class NoteEditor {
  constructor(element,onChange){this.el=element;this.onChange=onChange;this.runs=[];this.saved=[0,0];this.undo=[];this.redo=[];this.composing=false;
    Object.defineProperties(element,{value:{get:()=>RichText.text(this.read()),set:text=>this.load({id:this.id,text})},selectionStart:{get:()=>this.selection()[0]},selectionEnd:{get:()=>this.selection()[1]}});
    element.setSelectionRange=(a,b)=>this.select(a,b);
    document.addEventListener('selectionchange',()=>{const s=getSelection();if(s.rangeCount&&element.contains(s.anchorNode)&&element.contains(s.focusNode))this.saved=this.selection();});
    element.addEventListener('compositionstart',()=>this.composing=true);element.addEventListener('compositionend',()=>{this.composing=false;this.commitInput();});
    element.addEventListener('input',()=>{if(!this.composing)this.commitInput();});
    element.addEventListener('paste',e=>{e.preventDefault();this.insert(e.clipboardData.getData('text/plain'));});
    element.addEventListener('drop',e=>{if(e.dataTransfer.types.includes('text/html')||e.dataTransfer.types.includes('text/plain')){e.preventDefault();e.stopPropagation();this.insert(e.dataTransfer.getData('text/plain'));}});
    element.addEventListener('beforeinput',e=>{if(this.composing)return;const selection=this.selection();if(e.inputType.startsWith('delete')&&selection[0]===0&&selection[1]===RichText.text(this.read()).length&&selection[1]>0){e.preventDefault();this.change([],[0,0]);return;}if(e.inputType==='historyUndo'||e.inputType==='historyRedo'){e.preventDefault();this.history(e.inputType==='historyRedo');}if(e.inputType==='insertParagraph'||e.inputType==='insertLineBreak'){e.preventDefault();const [a,b]=this.selection(),t=RichText.text(this.read()),start=a===0?0:t.lastIndexOf('\n',a-1)+1,line=t.slice(start,a);if(/^[☐☑]\s*$/.test(line))this.change(RichText.replace(this.read(),start,b,[{text:'\n'}]),[start+1,start+1]);else this.insert(/^[☐☑]/.test(line)?'\n☐ ':'\n');}});
    element.addEventListener('keydown',e=>{if(this.composing)return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='a'){e.preventDefault();this.select(0,RichText.text(this.read()).length);return;}if((e.ctrlKey||e.metaKey)&&['z','y','b'].includes(e.key.toLowerCase())){e.preventDefault();if(e.key.toLowerCase()==='b'){const [a,b]=this.selection();if(a!==b)this.format('bold',!this.allBold());}else this.history(e.key.toLowerCase()==='y'||e.shiftKey);}if((e.key===' '||e.key==='Enter')&&e.target.classList.contains('todo-check')){e.preventDefault();this.toggle(e.target);}});
    element.addEventListener('click',e=>{if(e.target.classList.contains('todo-check'))this.toggle(e.target);});
  }
  read(){if(this.el.childNodes.length===1&&this.el.firstChild.nodeName==='BR')return [];const out=[];const walk=(node,style={})=>{if(node.nodeType===3){out.push({...style,text:node.data});return;}if(node.nodeType!==1)return;if(node.tagName==='BR'){out.push({text:'\n'});return;}const n={...style};if(node.style.fontWeight)n.bold=Number(node.style.fontWeight)>=600||node.style.fontWeight==='bold';if(node.tagName==='B'||node.tagName==='STRONG')n.bold=true;if(node.style.fontSize)n.size=parseFloat(node.style.fontSize);if(node.style.color){const c=node.style.color.match(/\d+/g);n.ink=c?'#'+c.slice(0,3).map(v=>(+v).toString(16).padStart(2,'0')).join(''):node.style.color;}if(['DIV','P'].includes(node.tagName)&&node!==this.el&&out.length&&!out.at(-1).text.endsWith('\n'))out.push({text:'\n'});for(const child of node.childNodes)walk(child,n);};for(const node of this.el.childNodes)walk(node);return RichText.normalize(out);}
  selection(){const s=getSelection();if(!s.rangeCount||!this.el.contains(s.anchorNode)||!this.el.contains(s.focusNode))return this.saved;const range=s.getRangeAt(0);const offset=(node,n)=>{const r=document.createRange();r.selectNodeContents(this.el);r.setEnd(node,n);return r.toString().length;};return [offset(range.startContainer,range.startOffset),offset(range.endContainer,range.endOffset)];}
  select(a,b=a){const length=RichText.text(this.read()).length;a=Math.min(a,length);b=Math.min(b,length);const point=offset=>{const walker=document.createTreeWalker(this.el,NodeFilter.SHOW_TEXT);let n;while(n=walker.nextNode()){if(offset<=n.length)return [n,offset];offset-=n.length;}return [this.el,this.el.childNodes.length];};const r=document.createRange();r.setStart(...point(a));r.setEnd(...point(b));const s=getSelection();s.removeAllRanges();s.addRange(r);this.saved=[a,b];}
  load(page){const runs=RichText.normalize(page.rich,page.text);if(this.id===page.id&&JSON.stringify(runs)===JSON.stringify(this.runs))return;const changed=this.id!==page.id;if(!changed){this.undo.push(this.snapshot());this.undo=this.undo.slice(-100);this.redo=[];}this.id=page.id;this.runs=runs;RichText.render(this.el,runs);if(changed){this.undo=[];this.redo=[];this.saved=[0,0];}else this.select(...this.saved);}
  snapshot(){return {runs:structuredClone(this.runs),selection:[...this.saved]};}
  commitInput(){const next=this.read();if(JSON.stringify(next)===JSON.stringify(this.runs))return;this.undo.push(this.snapshot());this.undo=this.undo.slice(-100);this.redo=[];this.runs=next;this.saved=this.selection();this.publish();}
  publish(){this.onChange({text:RichText.text(this.runs),rich:structuredClone(this.runs)});}
  change(runs,selection=this.selection()){this.undo.push(this.snapshot());this.undo=this.undo.slice(-100);this.redo=[];this.runs=RichText.normalize(runs);RichText.render(this.el,this.runs);this.el.focus();this.select(...selection);this.publish();}
  insert(text){const [a,b]=this.selection(),runs=this.read(),style=RichText.slice(runs,Math.max(0,a-1),a)[0]||{};this.change(RichText.replace(runs,a,b,[{...style,text}]),[a+text.length,a+text.length]);}
  format(key,value){const [a,b]=this.selection();if(a===b)return false;this.change(RichText.format(this.read(),a,b,{[key]:value}),[a,b]);return true;}
  allBold(){const [a,b]=this.selection(),base=getComputedStyle(this.el).fontWeight;return RichText.slice(this.read(),a,b).every(r=>r.bold??Number(base)>=600);}
  todo(){
    const [a,b]=this.selection(),runs=this.read(),text=RichText.text(runs),start=a===0?0:text.lastIndexOf('\n',a-1)+1;
    const starts=[start];for(let i=start;i<b;i++)if(text[i]==='\n'&&i+1<b)starts.push(i+1);
    const active=starts.filter(i=>starts.length===1||(text.slice(i,text.indexOf('\n',i)<0?text.length:text.indexOf('\n',i)).trim()!==''));
    const marked=i=>/[☐☑]/.test(text[i]||''),remove=active.length>0&&active.every(marked);let next=runs;
    for(const i of active.reverse()){if(remove)next=RichText.replace(next,i,i+(text[i+1]===' '?2:1),[]);else if(!marked(i))next=RichText.replace(next,i,i,[{text:'☐ '}]);}
    const pos=Math.max(0,Math.min(RichText.text(next).length,a+(remove?-1:2)));this.change(next,[pos,pos]);
  }
  toggle(node){const r=document.createRange();r.selectNodeContents(this.el);r.setEndBefore(node);const i=r.toString().length;this.change(RichText.replace(this.read(),i,i+1,[{...RichText.slice(this.read(),i,i+1)[0],text:node.textContent==='☐'?'☑':'☐'}]),this.saved);}
  history(redo){const from=redo?this.redo:this.undo,to=redo?this.undo:this.redo;if(!from.length)return;to.push(this.snapshot());const item=from.pop();this.runs=item.runs;RichText.render(this.el,this.runs);this.el.focus();this.select(...item.selection);this.publish();}
}
